#[cfg(feature = "alpha-transforms")]
pub mod redact_column;
pub mod sink_cluster;
pub mod sink_single;

use crate::connection::SinkConnection;
use crate::frame::Frame;
use crate::frame::postgres::{FrontendMessage, PostgresFrame};
use crate::message::{Message, Messages};
use anyhow::Result;

/// Returns true if a request makes the server produce output now.
///
/// The extended-query messages (Parse/Bind/Describe/Execute/Close) produce NO output until the
/// server sees a Flush or Sync — it buffers their responses. Everything else here elicits an
/// immediate response: the startup/auth exchange, a simple Query, Sync, Flush, and the COPY
/// terminators. An unparseable or non-postgres request is assumed to elicit a response so that a
/// batch is never mistaken for a buffered one (which would hang).
fn request_triggers_flush(request: &mut Message) -> bool {
    match request.frame() {
        Some(Frame::Postgres(PostgresFrame::Request(message))) => matches!(
            message,
            FrontendMessage::Startup { .. }
                | FrontendMessage::AuthenticationData(_)
                | FrontendMessage::Query { .. }
                | FrontendMessage::Sync
                | FrontendMessage::Flush
                | FrontendMessage::CopyDone
                | FrontendMessage::CopyFail { .. }
                | FrontendMessage::CancelRequest { .. }
        ),
        _ => true,
    }
}

/// Sends one batch of requests to a backend and reads the responses the server produces for it.
///
/// This exists because postgres buffers extended-protocol responses until it sees a Flush or Sync,
/// so a batch that contains no flush point produces NO responses yet. A naive
/// `while responses < requests` barrier deadlocks on such a batch: the sink waits forever for a
/// response the server will not send until a later Sync, and that later Sync can never be forwarded
/// because the task that would forward it is the one blocked here. TCP segmentation alone can split
/// a Parse from its Sync, so this is reachable with no misbehaving client.
///
/// `outstanding` tracks requests still awaiting a response ACROSS batches (each request eventually
/// yields exactly one response — a real one, or a dummy generated by the connection for messages the
/// server never answers). A batch that contains a flush point blocks until every outstanding
/// response has been read; a batch that does not returns immediately, and its responses arrive on
/// the batch that does carry the flush point.
pub(crate) async fn exchange(
    connection: &mut SinkConnection,
    mut requests: Messages,
    outstanding: &mut usize,
) -> Result<Messages> {
    let has_flush_point = requests.iter_mut().any(request_triggers_flush);
    *outstanding += requests.len();
    connection.send(requests)?;

    let mut responses = vec![];
    if has_flush_point {
        // The server will flush: read until every outstanding request has been answered.
        while *outstanding > 0 {
            let before = responses.len();
            connection.recv_into(&mut responses).await?;
            *outstanding = outstanding.saturating_sub(count_answered(&responses[before..]));
        }
    } else {
        // No flush point: grab any responses already available (e.g. the dummy responses the
        // connection generates for CopyData) but do not block on the server.
        let _ = connection.try_recv_into(&mut responses);
        *outstanding = outstanding.saturating_sub(count_answered(&responses));
    }
    Ok(responses)
}

/// The number of responses that answer a request (i.e. carry a request id). Unrequested responses
/// (asynchronous notices, parameter-status changes, notifications) do not decrement `outstanding`.
fn count_answered(responses: &[Message]) -> usize {
    responses
        .iter()
        .filter(|r| r.request_id().is_some())
        .count()
}
