#[cfg(feature = "alpha-transforms")]
pub mod redact_column;
pub mod sink_cluster;
pub mod sink_single;

use crate::connection::SinkConnection;
use crate::frame::Frame;
use crate::frame::postgres::{FrontendMessage, PostgresFrame};
use crate::message::{Message, Messages};
use anyhow::Result;
use std::time::Duration;

/// A backend accepted the connection but did not produce the next response within `read_timeout`.
/// Typed so a sink can turn it into a client ErrorResponse + connection close rather than letting the
/// client hang forever on a backend that stalls mid-answer.
#[derive(Debug)]
pub(crate) struct BackendReadTimeout;

impl std::fmt::Display for BackendReadTimeout {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "postgres backend did not respond within read_timeout")
    }
}

impl std::error::Error for BackendReadTimeout {}

/// Returns true if a request makes the server produce output now.
///
/// The extended-query messages (Parse/Bind/Describe/Execute/Close) produce NO output until the
/// server sees a Flush or Sync — it buffers their responses. Everything else here elicits an
/// immediate response: the startup/auth exchange, a simple Query, Sync, Flush, and the COPY
/// terminators. An unparseable or non-postgres request is assumed to elicit a response so that a
/// batch is never mistaken for a buffered one (which would hang).
fn request_triggers_flush(request: &mut Message) -> bool {
    match request.frame() {
        Some(Frame::Postgres(PostgresFrame::Request(message))) => matches!(
            message,
            FrontendMessage::Startup { .. }
                | FrontendMessage::AuthenticationData(_)
                | FrontendMessage::Query { .. }
                | FrontendMessage::Sync
                | FrontendMessage::Flush
                | FrontendMessage::CopyDone
                | FrontendMessage::CopyFail { .. }
                | FrontendMessage::CancelRequest { .. }
        ),
        _ => true,
    }
}

/// The number of trailing requests in a batch that CANNOT be answered yet.
///
/// Postgres flushes only what PRECEDES a flush point, so it is not enough to ask whether a batch
/// contains a flush point — a batch like `[Query, Parse]` or `[Sync, Parse]` flushes the Query/Sync
/// but buffers the trailing Parse until the next Flush/Sync. Blocking for that Parse's response
/// deadlocks (and swallows the Query's response with it), which is a TCP-coalescing shape a client
/// hits under load. This returns how many requests sit AFTER the last flush point, so the caller can
/// wait for everything up to and including that flush point and leave the trailing partial pipeline
/// outstanding for the next batch. `None` means the batch has no flush point at all — nothing it
/// sent can be answered until a later batch carries one.
fn trailing_unanswerable(requests: &mut [Message]) -> Option<usize> {
    requests
        .iter_mut()
        .rposition(request_triggers_flush)
        .map(|last_flush| requests.len() - 1 - last_flush)
}

/// Sends one batch of requests to a backend and reads the responses the server produces for it.
///
/// `outstanding` tracks requests still awaiting a response ACROSS batches (each request eventually
/// yields exactly one response — a real one, or a dummy generated by the connection for messages the
/// server never answers). The caller blocks only for the responses the server will actually flush
/// for this batch — everything up to and including its last flush point — and leaves any trailing
/// partial pipeline outstanding for the batch that carries the next flush point. A batch with no
/// flush point at all does not block: its responses arrive later.
pub(crate) async fn exchange(
    connection: &mut SinkConnection,
    mut requests: Messages,
    outstanding: &mut usize,
    read_timeout: Option<Duration>,
) -> Result<Messages> {
    let trailing = trailing_unanswerable(&mut requests);
    *outstanding += requests.len();
    connection.send(requests)?;

    let mut responses = vec![];
    match trailing {
        // The batch has a flush point: drain everything except the trailing partial pipeline.
        Some(trailing) => {
            while *outstanding > trailing {
                let before = responses.len();
                // read_timeout is an IDLE timeout: it bounds the wait for the NEXT chunk of response
                // data, resetting whenever data arrives, so a large legitimately-streaming result set
                // is never cut off — only a backend that stalls without producing anything trips it.
                match read_timeout {
                    Some(timeout) => {
                        tokio::time::timeout(timeout, connection.recv_into(&mut responses))
                            .await
                            .map_err(|_| BackendReadTimeout)??
                    }
                    None => connection.recv_into(&mut responses).await?,
                }
                *outstanding = outstanding.saturating_sub(count_answered(&responses[before..]));
            }
        }
        // No flush point: grab any responses already available (e.g. the dummy responses the
        // connection generates for CopyData) but do not block on the server.
        None => {
            let _ = connection.try_recv_into(&mut responses);
            *outstanding = outstanding.saturating_sub(count_answered(&responses));
        }
    }
    Ok(responses)
}

/// The number of responses that answer a request (i.e. carry a request id). Unrequested responses
/// (asynchronous notices, parameter-status changes, notifications) do not decrement `outstanding`.
fn count_answered(responses: &[Message]) -> usize {
    responses
        .iter()
        .filter(|r| r.request_id().is_some())
        .count()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn req(message: FrontendMessage) -> Message {
        Message::from_frame(Frame::Postgres(PostgresFrame::Request(message)))
    }

    fn query() -> FrontendMessage {
        FrontendMessage::Query {
            query: "SELECT 1".to_owned(),
        }
    }

    fn parse() -> FrontendMessage {
        FrontendMessage::Parse {
            statement_name: "".to_owned(),
            query: "SELECT 1".to_owned(),
            parameter_data_types: vec![],
        }
    }

    fn bind() -> FrontendMessage {
        FrontendMessage::Bind {
            portal_name: "".to_owned(),
            statement_name: "".to_owned(),
            parameter_format_codes: vec![],
            parameter_values: vec![],
            result_format_codes: vec![],
        }
    }

    fn batch(messages: Vec<FrontendMessage>) -> Vec<Message> {
        messages.into_iter().map(req).collect()
    }

    #[test]
    fn test_trailing_unanswerable() {
        // A flush point at the end: nothing trailing, drain everything.
        assert_eq!(trailing_unanswerable(&mut batch(vec![query()])), Some(0));
        assert_eq!(
            trailing_unanswerable(&mut batch(vec![parse(), FrontendMessage::Sync])),
            Some(0)
        );
        assert_eq!(
            trailing_unanswerable(&mut batch(vec![parse(), query()])),
            Some(0)
        );
        // A flush point followed by a buffered pipeline: those trailing messages cannot answer yet.
        // These are the coalesced-pipeline shapes that deadlocked the round-two fix.
        assert_eq!(
            trailing_unanswerable(&mut batch(vec![query(), parse()])),
            Some(1)
        );
        assert_eq!(
            trailing_unanswerable(&mut batch(vec![FrontendMessage::Sync, parse()])),
            Some(1)
        );
        assert_eq!(
            trailing_unanswerable(&mut batch(vec![FrontendMessage::Sync, parse(), bind()])),
            Some(2)
        );
        // No flush point at all: the whole batch is buffered, do not block.
        assert_eq!(trailing_unanswerable(&mut batch(vec![parse()])), None);
        assert_eq!(
            trailing_unanswerable(&mut batch(vec![parse(), bind()])),
            None
        );
    }
}
